version: '3'
services:
  frontend:
    image: frontend
    build:
      context: ./Frontend
    ports:
      - "2000:2000"
    networks:
      - bazarcom-network

  catalog:
    image: catalog-server 
    build:
      context: ./CatalogServer
    ports:
      - "2001:2001"  # Host port 2001 -> Catalog internal port 2001
    networks:
      - bazarcom-network

  catalogReplica:
    image: catalog-replica
    build:
      context: ./CatalogReplica 
    ports:
      - "2003:2001"  # Host port 2003 -> CatalogReplica internal port 2001
    networks:
      - bazarcom-network

  order:
    image: order-server  
    build:
      context: ./OrderServer
    ports:
      - "2002:2002"  # Host port 2002 -> Order internal port 2002
    networks:
      - bazarcom-network

  orderReplica:
    image: order-replica  
    build:
      context: ./OrderReplica 
    ports:
      - "2004:2002"  # Host port 2004 -> OrderReplica internal port 2002
    networks:
      - bazarcom-network

networks:
  bazarcom-network:
    driver: bridge
