version: '3'
services:
  frontend:
    image: frontend
    build:
      context: ./Frontend
    ports:
      - "1000:1000"
    networks:
      - bazarcom-network

  catalog:
    image: catalog-server 
    build:
      context: ./CatalogServer
    ports:
      - "1001:1001"  # Host port 2001 -> Catalog internal port 2001
    networks:
      - bazarcom-network

  catalogReplica:
    image: catalog-server 
    build:
      context: ./CatalogServer 
    ports:
      - "1003:1001"  # Host port 2003 -> CatalogReplica internal port 2001
    networks:
      - bazarcom-network

  order:
    image: order-server  
    build:
      context: ./OrderServer
    ports:
      - "1002:1002"  # Host port 2002 -> Order internal port 2002
    networks:
      - bazarcom-network

  orderReplica:
    image: order-server   
    build:
      context: ./OrderServer 
    ports:
      - "1004:1002"  # Host port 2004 -> OrderReplica internal port 2002
    networks:
      - bazarcom-network

networks:
  bazarcom-network:
    driver: bridge
