version: '3'
services:
  catalog:
    image: catalog-server
    build:
      context: ./CatalogServer
    ports:
      - "2001:2001"
    networks:
      - bazarcom-network  


  catalogReplica:
    image: catalog-server
    build:
      context: ./CatalogServer
    ports:
      - "2003:2001"
    networks:
      - bazarcom-network    

  order:
    image: order-server
    build:
      context: ./OrderServer
    ports:
      - "2002:2002"
    networks:
      - bazarcom-network


  orderReplica:
    image: order-server
    build:
      context: ./OrderServer
    ports:
      - "2004:2002"
    networks:
      - bazarcom-network    

  frontend:
    image: frontend
    build:
      context: ./Frontend
    ports:
      - "2000:2000"
    networks:
      - bazarcom-network

networks:
  bazarcom-network:
    driver: bridge